disabled_rules: # rule identifiers to exclude from running
identifier_name:
  min_length: 2 # because Identifiable required id

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Alfred/Components/SkyIconUIView.swift
  - Alfred/Helpers/HueColor.swift
